// helpers/IconHelper.js
import {
    FaBeer,
    FaCoffee,
    FaHome,
    FaApple,
    FaCar,
    FaCloud,
    FaHeart,
    FaBell,
    FaCamera,
    FaFlag,
    FaUser,
    FaStar,
    FaEnvelope,
    FaLightbulb,
    FaSearch,
    FaSmile,
    FaCog,
    FaAnchor,
    FaBasketballBall,
    FaBook,
    FaBriefcase,
    FaCalendar,
    FaChartBar,
    FaClipboard,
    FaClock,
    FaComments,
    FaCompass,
    FaCreditCard,
    FaDesktop,
    FaDumbbell,
    FaEdit,
    FaGlobe,
    FaGift,
    FaHeartBroken,
    FaHospital,
    FaKey,
    FaLaptop,
    FaLock,
    FaMapMarkerAlt,
    FaMoneyBillAlt,
    FaPaperPlane,
    FaPen,
    FaPhone,
    FaPhoneAlt,
    FaQuestionCircle,
    FaQuoteLeft,
    FaRocket,
    FaSearchPlus,
    FaShippingFast,
    FaShoppingCart,
    FaSlidersH,
    FaTag,
    FaThumbsUp,
    FaTools,
    FaTrash,
    FaTrophy,
    FaTruck,
    FaUmbrella,
    FaUserAlt,
    FaUsers,
    FaVideo,
    FaVolumeUp,
    FaWallet,
    FaWater,
    FaWifi,
    FaWrench,
  } from "react-icons/fa";
  
  export const iconList = [
    { name: "FaBeer", icon: FaBeer },
    { name: "FaCoffee", icon: FaCoffee },
    { name: "FaHome", icon: FaHome },
    { name: "FaApple", icon: FaApple },
    { name: "FaCar", icon: FaCar },
    { name: "FaCloud", icon: FaCloud },
    { name: "FaHeart", icon: FaHeart },
    { name: "FaBell", icon: FaBell },
    { name: "FaCamera", icon: FaCamera },
    { name: "FaFlag", icon: FaFlag },
    { name: "FaUser", icon: FaUser },
    { name: "FaStar", icon: FaStar },
    { name: "FaEnvelope", icon: FaEnvelope },
    { name: "FaLightbulb", icon: FaLightbulb },
    { name: "FaSearch", icon: FaSearch },
    { name: "FaSmile", icon: FaSmile },
    { name: "FaCog", icon: FaCog },
    { name: "FaAnchor", icon: FaAnchor },
    { name: "FaBasketballBall", icon: FaBasketballBall },
    { name: "FaBook", icon: FaBook },
    { name: "FaBriefcase", icon: FaBriefcase },
    { name: "FaCalendar", icon: FaCalendar },
    { name: "FaChartBar", icon: FaChartBar },
    { name: "FaClipboard", icon: FaClipboard },
    { name: "FaClock", icon: FaClock },
    { name: "FaComments", icon: FaComments },
    { name: "FaCompass", icon: FaCompass },
    { name: "FaCreditCard", icon: FaCreditCard },
    { name: "FaDesktop", icon: FaDesktop },
    { name: "FaDumbbell", icon: FaDumbbell },
    { name: "FaEdit", icon: FaEdit },
    { name: "FaGlobe", icon: FaGlobe },
    { name: "FaGift", icon: FaGift },
    { name: "FaHeartBroken", icon: FaHeartBroken },
    { name: "FaHospital", icon: FaHospital },
    { name: "FaKey", icon: FaKey },
    { name: "FaLaptop", icon: FaLaptop },
    { name: "FaLock", icon: FaLock },
    { name: "FaMapMarkerAlt", icon: FaMapMarkerAlt },
    { name: "FaMoneyBillAlt", icon: FaMoneyBillAlt },
    { name: "FaPaperPlane", icon: FaPaperPlane },
    { name: "FaPen", icon: FaPen },
    { name: "FaPhone", icon: FaPhone },
    { name: "FaPhoneAlt", icon: FaPhoneAlt },
    { name: "FaQuestionCircle", icon: FaQuestionCircle },
    { name: "FaQuoteLeft", icon: FaQuoteLeft },
    { name: "FaRocket", icon: FaRocket },
    { name: "FaSearchPlus", icon: FaSearchPlus },
    { name: "FaShippingFast", icon: FaShippingFast },
    { name: "FaShoppingCart", icon: FaShoppingCart },
    { name: "FaSlidersH", icon: FaSlidersH },
    { name: "FaTag", icon: FaTag },
    { name: "FaThumbsUp", icon: FaThumbsUp },
    { name: "FaTools", icon: FaTools },
    { name: "FaTrash", icon: FaTrash },
    { name: "FaTrophy", icon: FaTrophy },
    { name: "FaTruck", icon: FaTruck },
    { name: "FaUmbrella", icon: FaUmbrella },
    { name: "FaUserAlt", icon: FaUserAlt },
    { name: "FaUsers", icon: FaUsers },
    { name: "FaVideo", icon: FaVideo },
    { name: "FaVolumeUp", icon: FaVolumeUp },
    { name: "FaWallet", icon: FaWallet },
    { name: "FaWater", icon: FaWater },
    { name: "FaWifi", icon: FaWifi },
    { name: "FaWrench", icon: FaWrench }
  ];
  